language: cpp

branches:
  only:
    - master
    - master_coverity_scan
    - /^stable-.*$/

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - wget --no-check-certificate http://www.cmake.org/files/v3.1/cmake-3.1.2-Linux-x86_64.sh
  - sudo bash ./cmake-3.1.2-Linux-x86_64.sh --prefix=/usr/local/ --skip-license --exclude-subdir
  - sudo add-apt-repository ppa:libreoffice/ppa --yes
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' --yes
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa --yes
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq --force-yes g++-4.9; else sudo apt-get install -qq --force-yes clang-3.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; else export CXX="clang++-3.8" CC="clang-3.8"; fi
  - sudo apt-get install -qq --force-yes cmake qtbase5-dev qt5-qmake libqt5core5 libqt5widgets5 libqt5gui5 qttools5-dev libqt5svg5-dev libqt5network5 libqt5printsupport5 libqt5xml5 libqt5webkit5-dev libqt5declarative5 qtquick1-5-dev libqt5qml5 libqt5quick5 qtdeclarative5-dev qtdeclarative5-dev-tools libqt5opengl5-dev qtlocation5-dev qtsensors5-dev qtchooser qttools5-dev-tools libclucene-dev
  - sudo sed -e 's/class Q_CORE_EXPORT QUrl/class QUrl;\nQ_CORE_EXPORT uint qHash(const QUrl \&url, uint seed = 0) Q_DECL_NOTHROW;\n&/' -e 's/\(friend Q_CORE_EXPORT uint qHash(const .*, uint seed\) = 0/\1/' -i /usr/include/qt5/QtCore/qurl.h || true
  - sudo sed -e 's/class Q_CORE_EXPORT QPersistentModelIndex/class QPersistentModelIndex;\nQ_CORE_EXPORT uint qHash(const QPersistentModelIndex \&, uint seed = 0);\n&/' -e 's/\(friend uint qHash(const .*, uint seed\) = 0/\1/' -i /usr/include/qt5/QtCore/qabstractitemmodel.h || true
  - sudo sed -e 's/class Q_NETWORK_EXPORT QHostAddress/class QHostAddress;\nQ_NETWORK_EXPORT uint qHash(const QHostAddress \&, uint seed = 0);\n&/' -e 's/\(friend Q_NETWORK_EXPORT uint qHash(const .*, uint seed\) = 0/\1/' -i /usr/include/qt5/QtNetwork/qhostaddress.h || true
  - svn checkout --non-interactive http://crosswire.org/svn/sword/trunk sword-trunk
  - cd sword-trunk
  - mkdir b
  - cd b
  - cmake ..
  - make
  - sudo make install
  - cd ../..

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mkdir b && cd b && /usr/local/bin/cmake .. && make && sudo make install; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VjsU8+6Sca7TXbR5zQstHw6eb4Dv0ZifqE29DRT+n64VKxAWFaWazJ4VJNlHvd8ChiJRfFcXVVXfNgNMAHE/JJHt1GgSPwIqSEE2mQh+7tqfSeBV/5yBkF7Fs4QIOrWjdEhEHTt0+wc6wtoVghEHvWlk3Lymb4x0UQDZtz/a4cI="

addons:
  coverity_scan:
    project:
      name: "bibletime/bibletime"
      description: "BibleTime build submitted via Travis CI"
    notification_email: bibletime-coverity@heh.ee
    build_command_prepend: "mkdir b && cd b && /usr/local/bin/cmake .."
    build_command: "make"
    branch_pattern: .*_coverity_scan

notifications:
  irc: "chat.freenode.net#bibletime"
